### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by Wetrain** [kennethreitz/pipenv#643]
Hi there, i've just installed pipenv onto a Debian machine, i'm still very new to pipenv as i've only ever used Virtualenv.

The above error was produced when following the pipenv command list, the command i run was:

'pipenv --where'

Which produced the following stack trace:

```
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.5/dist-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/pipenv/vendor/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/usr/local/lib/python3.5/dist-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pipenv/vendor/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pipenv/cli.py", line 1301, in cli
    do_where(bare=bare)
  File "/usr/local/lib/python3.5/dist-packages/pipenv/cli.py", line 567, in do_where
    location = shorten_path(location)
  File "/usr/local/lib/python3.5/dist-packages/pipenv/cli.py", line 550, in shorten_path
    short = os.sep.join([s[0] if len(s) > (len('2long4')) else s for s in location.split(os.sep)])
AttributeError: 'NoneType' object has no attribute 'split'

```

**Comment by Wetrain** [comment]
** As a footnote, i'm new to the Open Source world and would very much like to see if i could submit a patch if this turns out to be a bug with cli.py.

**Comment by techalchemy** [comment]
`pipenv --where` is a command that shows you the location of your `Project virtualenv`.  Projects are a pipenv construct to track metadata about your environment, and pipenv handles a lot of things on the backend for you.  If you run `pipenv --where` in a directory with no Pipfile and which is not managed by pipenv, it will error out.  You can't find a virtualenv for a project that doesn't exist

**Comment by techalchemy** [comment]
That said, the latest version of pipenv actually handles the case I described.  Can you provide the output of `pipenv --version`, the path where you ran `pipenv --where` , your Pipfile or requirements.txt if applicable

**Comment by Wetrain** [comment]
Hi techalchemy,

I'm currently running: pipenv, version 7.2.6

**Comment by techalchemy** [comment]
You’re a bunch of versions behind (updates are happening rapidly) - update and see if it is fixed

**Comment by Wetrain** [comment]
Fixed in the latest version, thanks!

**Comment by MarwaDF** [comment]
Any help about this please ? I am using python 3.5 anaconda

filter_sizes=list(map(int, FLAGS.filter_sizes.split(","))),

AttributeError: 'NoneType' object has no attribute 'split'

**Comment by techalchemy** [comment]
@MarwaDF your error message and this issue are not even a little bit related. Please open a new issue

**Comment by MarwaDF** [comment]
i need to use python 2.7 with tensorflow on windows, after a search i found
that python2 is not supported with tensorflow in windows, so i have
installed python 3.5 which supports tensorflow, but i still have this error



2018-04-02 16:37 GMT+02:00 Dan Ryan <notifications@github.com>:

**Comment by techalchemy** [comment]
@MarwaDF this is not a pipenv issue. Please file an issue with tensorflow or see the tensorflow docs or post your question on stack overflow.
