### ISSUE TITLE
git remote address modified changing underscore to a hyphen...

### ISSUE THREAD

**Issue by minskmaz** [kennethreitz/pipenv#788]
I noticed that after pipenv announces successful install of a private repo from gitlab:

pipenv install -e git+git@gitlab.com:_orangenero/db.git#egg=db;

... I get an error from pip

pip.exceptions.InstallationError: Command "git clone -q git@gitlab.com:-orangenero/db.git /tmp/pip-8ySH2I-export" failed with error code 128 in None

Notice pip has been passed a modified gitlab groupname that transforms the underscore to a hyphen. In this case:

"_orangenero" to "-orangenero"

or, 

git clone -q git@gitlab.com:-orangenero/db.git /tmp/pip-8ySH2I-export

**Comment by nateprewitt** [comment]
@minskmaz, I believe we addressed this late in the 7.X releases or early 8.X. Could you please provide the version of pipenv you're currently using?

**Comment by minskmaz** [comment]
pipenv, version 8.2.5

**Comment by minskmaz** [comment]
@nateprewitt pipenv, version 8.2.5

**Comment by erinxocon** [comment]
Can reproduce.  Working on a fix now.

**Comment by kennethreitz** [comment]
fix merged

**Comment by minskmaz** [comment]
Thank you @nateprewitt / @kennethreitz but I'm not certain its fixed. I'm now on version 8.2.6 as you see here:

Removing intermediate container e57341c44ad5
Step 10/15 : RUN pipenv --version
 ---> Running in f93d1756481f
pipenv, version 8.2.6

But I am still getting the pip error below after pipenv installs the egg:

Installing -e git+git@gitlab.com:_orangenero/allspark.git#egg=allspark…
Obtaining allspark from git+git@gitlab.com:_orangenero/allspark.git#egg=allspark
  Updating /root/.local/share/virtualenvs/iota-9BD0xIDx/src/allspark clone
Installing collected packages: allspark
  Found existing installation: allspark 0.0.post0.dev7+ng5af9e93
    Uninstalling allspark-0.0.post0.dev7+ng5af9e93:
      Successfully uninstalled allspark-0.0.post0.dev7+ng5af9e93
  Running setup.py develop for allspark
Successfully installed allspark

Adding -e git+git@gitlab.com:_orangenero/allspark.git#egg=allspark to Pipfile's [packages]…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
fatal: strange pathname '-orangenero/allspark.git' blocked
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/cli.py", line 1852, in install
    do_lock(system=system, pre=pre)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/cli.py", line 1083, in do_lock
    pre=pre
  File "/usr/local/lib/python2.7/dist-packages/pipenv/utils.py", line 421, in resolve_deps
    resolved_tree.update(resolver.resolve(max_rounds=PIPENV_MAX_ROUNDS))
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/piptools/resolver.py", line 101, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/piptools/resolver.py", line 199, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/piptools/resolver.py", line 274, in _iter_dependencies
    for dependency in self.repository.get_dependencies(ireq):
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/piptools/repositories/pypi.py", line 171, in get_dependencies
    result = reqset._prepare_file(self.finder, ireq)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/pip/req/req_set.py", line 521, in _prepare_file
    req_to_install.update_editable(not self.is_download)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/pip/req/req_install.py", line 587, in update_editable
    vcs_backend.export(self.source_dir)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/pip/vcs/git.py", line 69, in export
    self.unpack(temp_dir)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/pip/vcs/__init__.py", line 286, in unpack
    self.obtain(location)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/pip/vcs/git.py", line 142, in obtain
    self.run_command(['clone', '-q', url, dest])
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/pip/vcs/__init__.py", line 325, in run_command
    spinner)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command "git clone -q git@gitlab.com:-orangenero/allspark.git /tmp/pip-Gniraz-export" failed with error code 128 in None
Installing -e git+git@gitlab.com:_orangenero/scheduler.git#egg=scheduler…

**Comment by techalchemy** [comment]
With the current release I am getting this error when I try to install your package:

```fish
 /t/new  pipenv install -e git+git@gitlab.com:_orangenero/db.git#egg=db                                                                                                            Sun 01 Oct 2017 07:24:50 PM EDT
Installing -e git+git@gitlab.com:_orangenero/db.git#egg=db…
Obtaining db from git+git@gitlab.com:_orangenero/db.git#egg=db
  Cloning git@gitlab.com:_orangenero/db.git to /home/hawk/.local/share/virtualenvs/new-X2WGxJLe/src/db
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

pip.exceptions.InstallationError: Command "git clone -q git@gitlab.com:_orangenero/db.git /home/hawk/.local/share/virtualenvs/new-X2WGxJLe/src/db" failed with error code 128 in None

Error:  An error occurred while installing -e git+git@gitlab.com:_orangenero/db.git#egg=db!
Command "git clone -q git@gitlab.com:_orangenero/db.git /home/hawk/.local/share/virtualenvs/new-X2WGxJLe/src/db" failed with error code 128 in None
```

There doesn't seem to be anything in the codebase that would still cause this translation to occur

**Comment by erinxocon** [comment]
I think it is a private package, I couldn't clone it either.

**Comment by erinxocon** [comment]
There is another little fix for this that will be in the next release!

**Comment by techalchemy** [comment]
Can you point me at the hash? I know it was private but the relevant bit was that the InstallationError didn't replace the _ in the clone command

**Comment by minskmaz** [comment]
Apologies. This should work for you now. I used PyScaffold to generate myspecialpackage. I just made this - so it's public
 
https://gitlab.com/_orangenero/myspecialpackage

**Comment by erinxocon** [comment]
I can check tomorrow morning.  Thanks for making the link public!

**Comment by techalchemy** [comment]
URL replacement still is not happening for me using the current release of pipenv -- is there a change that was already pushed and released? If so can you point me at the hash for it?  Just curious as to what code would be doing this, I couldn't find it

@minskmaz are you sure you have the right version?  Maybe try to uninstall and reinstall pipenv with `--no-cache-dir`

```ShellSession
$ pipenv install -e git+https://gitlab.com/_orangenero/myspecialpackage.git#egg=myspecialpackage
Installing -e git+https://gitlab.com/_orangenero/myspecialpackage.git#egg=myspecialpackage…
Obtaining myspecialpackage from git+https://gitlab.com/_orangenero/myspecialpackage.git#egg=myspecialpackage
  Cloning https://gitlab.com/_orangenero/myspecialpackage.git to /home/hawk/.local/share/virtualenvs/new-X2WGxJLe/src/myspecialpackage
Installing collected packages: myspecialpackage
  Running setup.py develop for myspecialpackage
Successfully installed myspecialpackage

Adding -e git+https://gitlab.com/_orangenero/myspecialpackage.git#egg=myspecialpackage to Pipfile's [packages]…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Updated Pipfile.lock (032075)!
$ pipenv --version                                                                                                                                                  
pipenv, version 8.2.6
```

**Comment by minskmaz** [comment]
Did as you suggested:
```
Collecting pipenv
  Downloading pipenv-8.2.6.tar.gz (3.7MB)
```

Still get this:

```
Virtualenv location: /root/.local/share/virtualenvs/iota-9BD0xIDx
Requirements file provided! Importing into Pipfile…
Installing dependencies from Pipfile.lock (342c3e)…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 95/95 — 00:05:49
To activate this project's virtualenv, run the following:
 $ pipenv shell
Installing -e git+git@gitlab.com:_orangenero/allspark.git#egg=allspark…
Obtaining allspark from git+git@gitlab.com:_orangenero/allspark.git#egg=allspark
  Cloning git@gitlab.com:_orangenero/allspark.git to /root/.local/share/virtualenvs/iota-9BD0xIDx/src/allspark
Installing collected packages: allspark
  Running setup.py develop for allspark
Successfully installed allspark

Adding -e git+git@gitlab.com:_orangenero/allspark.git#egg=allspark to Pipfile's [packages]…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
fatal: strange pathname '-orangenero/allspark.git' blocked
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 11, in <module>
    load_entry_point('pipenv==8.2.6', 'console_scripts', 'pipenv')()
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/cli.py", line 1852, in install
    do_lock(system=system, pre=pre)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/cli.py", line 1083, in do_lock
    pre=pre
  File "/usr/local/lib/python2.7/dist-packages/pipenv/utils.py", line 421, in resolve_deps
    resolved_tree.update(resolver.resolve(max_rounds=PIPENV_MAX_ROUNDS))
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/piptools/resolver.py", line 101, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/piptools/resolver.py", line 199, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/piptools/resolver.py", line 274, in _iter_dependencies
    for dependency in self.repository.get_dependencies(ireq):
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/piptools/repositories/pypi.py", line 171, in get_dependencies
    result = reqset._prepare_file(self.finder, ireq)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/pip/req/req_set.py", line 521, in _prepare_file
    req_to_install.update_editable(not self.is_download)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/pip/req/req_install.py", line 587, in update_editable
    vcs_backend.export(self.source_dir)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/pip/vcs/git.py", line 69, in export
    self.unpack(temp_dir)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/pip/vcs/__init__.py", line 286, in unpack
    self.obtain(location)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/pip/vcs/git.py", line 142, in obtain
    self.run_command(['clone', '-q', url, dest])
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/pip/vcs/__init__.py", line 325, in run_command
    spinner)
  File "/usr/local/lib/python2.7/dist-packages/pipenv/patched/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command "git clone -q git@gitlab.com:-orangenero/allspark.git /tmp/pip-mAzkz2-export" failed with error code 128 in None
Installing -e git+git@gitlab.com:_orangenero/scheduler.git#egg=scheduler…

```

**Comment by minskmaz** [comment]
@techalchemy this is all occuring in a docker container and my version is 8.2.6 as you can see directly above

**Comment by techalchemy** [comment]
Huh.   What if you use git+https?  does it still fail?  I'm just wondering why it worked for me and not for you

**Comment by erinxocon** [comment]
@minskmaz Can you post your Dockerfile?  Working on a fix, think I know what's wrong here

**Comment by minskmaz** [comment]
@erinxocon you may have to tweak it for your environment. 

https://gist.github.com/minskmaz/f67f75e0fc258f09eff3c59c80915f9a

**Comment by minskmaz** [comment]
@kennethreitz @erinxocon I've verified that this bug(?) lives on. You should be able to reproduce it with this shell script.

https://gist.github.com/minskmaz/572884f38f194389fddbd716d100077f

**Comment by techalchemy** [comment]
Since you didn't test with `git+https` I went ahead and created an account on gitlab just for the purpose of troubleshooting this.

When I use pipenv to install over `git+https` I have no issues:

```shell
 ◰³ tempenv-6b109962c2c  /t/new  pipenv install -e git+https://gitlab.com/_orangenero/myspecialpackage.git#egg=myspecialpackage
Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project.
Creating a Pipfile for this project…
Installing -e git+https://gitlab.com/_orangenero/myspecialpackage.git#egg=myspecialpackage…
Obtaining myspecialpackage from git+https://gitlab.com/_orangenero/myspecialpackage.git#egg=myspecialpackage
  Cloning https://gitlab.com/_orangenero/myspecialpackage.git to /home/hawk/.virtualenvs/tempenv-6b109962c2c/src/myspecialpackage
Installing collected packages: myspecialpackage
  Found existing installation: myspecialpackage 0.0.post0.dev1+ng9cde9d5
    Uninstalling myspecialpackage-0.0.post0.dev1+ng9cde9d5:
      Successfully uninstalled myspecialpackage-0.0.post0.dev1+ng9cde9d5
  Running setup.py develop for myspecialpackage
Successfully installed myspecialpackage

Adding -e git+https://gitlab.com/_orangenero/myspecialpackage.git#egg=myspecialpackage to Pipfile's [packages]…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Updated Pipfile.lock (032075)!
```

However, now that I have an account with gitlab and have registered my pubkey I can actually attempt this over ssh and I am experiencing the mentioned substitution:

```shell
◰³ tempenv-6b109962c2c  /t/new  pipenv install -e git+git@gitlab.com:_orangenero/myspecialpackage.git#egg=myspecialpackage
Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project.
Installing -e git+git@gitlab.com:_orangenero/myspecialpackage.git#egg=myspecialpackage…
Obtaining myspecialpackage from git+git@gitlab.com:_orangenero/myspecialpackage.git#egg=myspecialpackage
  Cloning git@gitlab.com:_orangenero/myspecialpackage.git to /home/hawk/.virtualenvs/tempenv-6b109962c2c/src/myspecialpackage
Installing collected packages: myspecialpackage
  Running setup.py develop for myspecialpackage
Successfully installed myspecialpackage

Adding -e git+git@gitlab.com:_orangenero/myspecialpackage.git#egg=myspecialpackage to Pipfile's [packages]…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
fatal: strange pathname '-orangenero/myspecialpackage.git' blocked
Traceback (most recent call last):
  File "/home/hawk/.pyenv/versions/3.6.2/bin/pipenv", line 11, in <module>
    load_entry_point('pipenv==8.2.6', 'console_scripts', 'pipenv')()
  File "/home/hawk/.pyenv/versions/3.6.2/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/hawk/.pyenv/versions/3.6.2/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/hawk/.pyenv/versions/3.6.2/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/hawk/.pyenv/versions/3.6.2/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/hawk/.pyenv/versions/3.6.2/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/hawk/.pyenv/versions/3.6.2/lib/python3.6/site-packages/pipenv/cli.py", line 1852, in install
    do_lock(system=system, pre=pre)
  File "/home/hawk/.pyenv/versions/3.6.2/lib/python3.6/site-packages/pipenv/cli.py", line 1083, in do_lock
    pre=pre
  File "/home/hawk/.pyenv/versions/3.6.2/lib/python3.6/site-packages/pipenv/utils.py", line 421, in resolve_deps
    resolved_tree.update(resolver.resolve(max_rounds=PIPENV_MAX_ROUNDS))
  File "/home/hawk/.pyenv/versions/3.6.2/lib/python3.6/site-packages/pipenv/patched/piptools/resolver.py", line 101, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/home/hawk/.pyenv/versions/3.6.2/lib/python3.6/site-packages/pipenv/patched/piptools/resolver.py", line 199, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "/home/hawk/.pyenv/versions/3.6.2/lib/python3.6/site-packages/pipenv/patched/piptools/resolver.py", line 274, in _iter_dependencies
    for dependency in self.repository.get_dependencies(ireq):
  File "/home/hawk/.pyenv/versions/3.6.2/lib/python3.6/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 171, in get_dependencies
    result = reqset._prepare_file(self.finder, ireq)
  File "/home/hawk/.pyenv/versions/3.6.2/lib/python3.6/site-packages/pipenv/patched/pip/req/req_set.py", line 521, in _prepare_file
    req_to_install.update_editable(not self.is_download)
  File "/home/hawk/.pyenv/versions/3.6.2/lib/python3.6/site-packages/pipenv/patched/pip/req/req_install.py", line 587, in update_editable
    vcs_backend.export(self.source_dir)
  File "/home/hawk/.pyenv/versions/3.6.2/lib/python3.6/site-packages/pipenv/patched/pip/vcs/git.py", line 69, in export
    self.unpack(temp_dir)
  File "/home/hawk/.pyenv/versions/3.6.2/lib/python3.6/site-packages/pipenv/patched/pip/vcs/__init__.py", line 286, in unpack
    self.obtain(location)
  File "/home/hawk/.pyenv/versions/3.6.2/lib/python3.6/site-packages/pipenv/patched/pip/vcs/git.py", line 142, in obtain
   self.run_command(['clone', '-q', url, dest])
  File "/home/hawk/.pyenv/versions/3.6.2/lib/python3.6/site-packages/pipenv/patched/pip/vcs/__init__.py", line 325, in run_command
    spinner)
  File "/home/hawk/.pyenv/versions/3.6.2/lib/python3.6/site-packages/pipenv/patched/pip/utils/__init__.py", line 707, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip.exceptions.InstallationError: Command "git clone -q git@gitlab.com:-orangenero/myspecialpackage.git /tmp/pip-ljsuskl2-export" failed with error code 128 in None
```

**Comment by techalchemy** [comment]
I see the issue.  The library we are using for requirements parsing doesn't accurately flag this as a VCS path because it isn't written as `git+git://gitlab.com`

I'll submit a PR to address this in pipenv but I don't know if that's the right place to address it

**Comment by minskmaz** [comment]
Thank you for taking the time to track down the problem. I will revert to https. I suppose this would have kept popping up so at least it’ll be resolved upstream that much sooner.

**Comment by techalchemy** [comment]
hm I can't actually test my fix right now since the sample package fails with setup.py egg_info.  I'll push a change for now and see if I can replicate

**Comment by techalchemy** [comment]
OK in order to test this I actually created my own private group starting with a leading underscore and installed an existing package with a working setup.py:

```shell
 ◰³ tempenv-6b109962c2c  /t/new  pipenv install -e git+git@gitlab.com:_sensei/django-select2.git#egg=django-select2
Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project.
Creating a Pipfile for this project…
Installing -e git+git@gitlab.com:_sensei/django-select2.git#egg=django-select2…
Obtaining django-select2 from git+git@gitlab.com:_sensei/django-select2.git#egg=django-select2
  Updating /home/hawk/.virtualenvs/tempenv-6b109962c2c/src/django-select2 clone
Requirement already satisfied: django-appconf>=0.6.0 in /home/hawk/.virtualenvs/tempenv-6b109962c2c/lib/python3.6/site-packages (from django-select2)
Installing collected packages: django-select2
  Running setup.py develop for django-select2
Successfully installed django-select2

Adding -e git+git@gitlab.com:_sensei/django-select2.git#egg=django-select2 to Pipfile's [packages]…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Updated Pipfile.lock (b5da3c)!
 ◰³ tempenv-6b109962c2c  /t/new    
```

So I can say that #835 will fix this when it is merged

**Comment by minskmaz** [comment]
@erinxocon @kennethreitz @nateprewitt @techalchemy -  I remember now why I chose not to use git https urls for python builds. When I insert my personal token in the url (for gitlab at least) it ends up getting spit out in the logs. Is there a way to suppress this in pipenv or at least to substitute the value for "gitlab-ci-token" with an 'xxx' ?  I know this verges on writing vendor specific code but perhaps a flag to pass log output to a function for postprocessing ??

pipenv install -e git+https://gitlab-ci-token:${dckr_gitlab_personal_access_token}@gitlab.com/_orangenero/endpoints.git#egg=endpoints
